---
- name: "Testing"
  hosts: localhost
  gather_facts: false

  tasks:

  - name: "Yadda yadda"
    community.aws.ec2_instance:
      region: "us-east-2"
      state: absent
      wait: false
      filters:
        "tag:mysidlabs_owner": "siduser299"
...
